include /etc/nginx/modules/*.conf;

worker_processes auto;
error_log /dev/stderr warn;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

stream {
    limit_conn_zone $binary_remote_addr zone=terraria_addr:10m;

    log_format basic '$remote_addr [$time_local] $protocol $status '
                     '$bytes_sent $bytes_received $session_time';
    access_log /dev/stdout basic;

    upstream terraria {
        server terraria-server:7777;
    }

    server {
        listen 7777;
        proxy_pass terraria;

        limit_conn terraria_addr ${TCP_GUARD_MAX_CONN};
        proxy_timeout ${TCP_GUARD_PROXY_TIMEOUT};
        proxy_connect_timeout ${TCP_GUARD_CONNECT_TIMEOUT};
        preread_timeout ${TCP_GUARD_PREREAD_TIMEOUT};
        tcp_nodelay on;
    }
}